### ISSUE TITLE
Missing pkg-config on MacOS

### ISSUE THREAD

**Issue by Deseteral** [felixc/gexiv2-sys#17]
Hi! First of all - thank you for your good work on bringing Exiv2 to Rust! 😄 

When I've tried building project that has `rexiv2` specified as dependency I ran into an issue with:
```The gexiv2 library was not found by pkg-config on your system.```

I've installed `gexiv2` using brew and exported `PKG_CONFIG_PATH` just like the readme says, but that wasn't enough. Turns out I also had to install `pkg-config` (using `brew install pkg-config`).

It would be nice if the readme or build script message said that you need to install it.
What do you think? Let me know, and I will make PR with that change 😄

**Comment by felixc** [comment]
Hi, and thanks for the report!

Was there by any chance a stack trace or anything printed after that error message (the "`The gexiv2 library was not found by pkg-config on your system.`" one)?

I don't have access to a Mac system to confirm this, but certainly would be happy to have an update to the setup docs! I think this section here would need `pkg-config` added to the `brew` command, and also the `PKG_CONFIG_PATH` step should be documented: https://github.com/felixc/gexiv2-sys/blob/master/SETUP.md#mac-os-x

For reference, the TravisCI setup that runs on Mac and Linux looks like this: https://github.com/felixc/gexiv2-sys/blob/master/.travis.yml. Notably, it sets `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"`

Thanks again for reporting the problem, and I'd be very happy to land a PR with these improvements to the docs!

**Comment by felixc** [comment]
I just remembered I did add something for `PKG_CONFIG_PATH` on the rexiv2 repo; that might be a starting point for this one: https://github.com/felixc/rexiv2/blob/master/SETUP.md#mac-os-x

**Comment by Deseteral** [comment]
Sorry for the late reply 😕 

The problem is that `/usr/local/opt/libffi/lib/pkgconfig` was missing. I had to run `brew install pkg-config` first. After that I set `PKG_CONFIG_PATH` and everything was fine.

I think adding this one `brew install` to the README should be enough.

**Comment by felixc** [comment]
Thanks for the report; I just added the missing package!
